name: Auto Merge New Requests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge-request:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout forked PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate file location
        id: validate
        run: |
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $changed_files"

          count=$(echo "$changed_files" | wc -l)
          only_requests=$(echo "$changed_files" | grep -Ec '^requests/[^/]+\.txt$')

          if [[ "$count" -eq "$only_requests" ]]; then
            echo "All changes are valid .txt files in requests folder."
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "Invalid changes detected."
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout upstream repo
        if: steps.validate.outputs.valid == 'true'
        uses: actions/checkout@v3
        with:
          repository: anshuverma-design/BulkGoogleGen
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR automatically
        if: steps.validate.outputs.valid == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
